# tickers.py
# 大型株TOP100（日本）＋大型株TOP100（米国）＝200銘柄

TICKERS = {

    # ============================
    # 🇯🇵 日本株（TOPIX Core30 + Large70）
    # ============================

    # --- Core30（30銘柄） ---
    "7203.T": "トヨタ自動車",
    "6758.T": "ソニーグループ",
    "8035.T": "東京エレクトロン",
    "6861.T": "キーエンス",
    "9983.T": "ファーストリテイリング",
    "9432.T": "NTT",
    "9433.T": "KDDI",
    "8306.T": "三菱UFJフィナンシャルグループ",
    "8316.T": "三井住友フィナンシャルグループ",
    "4502.T": "武田薬品工業",
    "6098.T": "リクルート",
    "7974.T": "任天堂",
    "6501.T": "日立製作所",
    "9984.T": "ソフトバンクグループ",
    "8058.T": "三菱商事",
    "8001.T": "伊藤忠商事",
    "8053.T": "住友商事",
    "8766.T": "東京海上HD",
    "4661.T": "オリエンタルランド",
    "6902.T": "デンソー",
    "6981.T": "村田製作所",
    "6594.T": "日本電産",
    "7741.T": "HOYA",
    "9101.T": "日本郵船",
    "9107.T": "川崎汽船",
    "9104.T": "商船三井",
    "5411.T": "JFEホールディングス",
    "5401.T": "日本製鉄",
    "4503.T": "アステラス製薬",

    # --- Large70（70銘柄） ---
    "2503.T": "キリンHD",
    "2502.T": "アサヒグループHD",
    "2914.T": "日本たばこ産業",
    "3382.T": "セブン＆アイHD",
    "3092.T": "ZOZO",
    "3289.T": "東急不動産HD",
    "3407.T": "旭化成",
    "3401.T": "帝人",
    "3861.T": "王子HD",
    "3863.T": "日本製紙",
    "4063.T": "信越化学工業",
    "4188.T": "三菱ケミカルグループ",
    "4208.T": "宇部興産",
    "4452.T": "花王",
    "4506.T": "大日本住友製薬",
    "4519.T": "中外製薬",
    "4523.T": "エーザイ",
    "4543.T": "テルモ",
    "4578.T": "大塚HD",
    "4901.T": "富士フイルムHD",
    "4911.T": "資生堂",
    "5020.T": "ENEOS",
    "5108.T": "ブリヂストン",
    "5201.T": "AGC",
    "5214.T": "日本電気硝子",
    "5332.T": "TOTO",
    "5406.T": "神戸製鋼所",
    "5413.T": "日鉄物産",
    "5713.T": "住友金属鉱山",
    "5802.T": "住友電気工業",
    "5803.T": "フジクラ",
    "5901.T": "東洋製罐グループHD",
    "6099.T": "エラン",
    "6301.T": "コマツ",
    "6367.T": "ダイキン工業",
    "6471.T": "日本精工",
    "6473.T": "ジェイテクト",
    "6503.T": "三菱電機",
    "6504.T": "富士電機",
    "6506.T": "安川電機",
    "6586.T": "マキタ",
    "6645.T": "オムロン",
    "6674.T": "ジャパンディスプレイ",
    "6723.T": "ルネサスエレクトロニクス",
    "6752.T": "パナソニックHD",
    "6754.T": "アンリツ",
    "6762.T": "TDK",
    "6770.T": "アルプスアルパイン",
    "6841.T": "横河電機",
    "6857.T": "アドバンテスト",
    "6901.T": "日立メタル",
    "6954.T": "ファナック",
    "6971.T": "京セラ",
    "7011.T": "三菱重工業",
    "7012.T": "川崎重工業",
    "7201.T": "日産自動車",
    "7267.T": "ホンダ",
    "7270.T": "SUBARU",
    "7731.T": "ニコン",
    "7733.T": "オリンパス",
    "7751.T": "キヤノン",
    "8031.T": "三井物産",
    "8113.T": "ユニ・チャーム",
    "8267.T": "イオン",
    "8308.T": "りそなHD",
    "8411.T": "みずほフィナンシャルグループ",
    "8591.T": "オリックス",
    "8769.T": "アドバンスクリエイト",
    "8802.T": "三菱地所",
    "9020.T": "JR東日本",
    "9022.T": "JR東海",
    "9021.T": "JR西日本",

    # ============================
    # 🇺🇸 米国株（S&P500 時価総額上位100）
    # ============================

    "AAPL": "Apple",
    "MSFT": "Microsoft",
    "AMZN": "Amazon",
    "NVDA": "NVIDIA",
    "META": "Meta Platforms",
    "GOOGL": "Alphabet Class A",
    "GOOG": "Alphabet Class C",
    "TSLA": "Tesla",
    "BRK.B": "Berkshire Hathaway",
    "UNH": "UnitedHealth Group",
    "XOM": "Exxon Mobil",
    "JNJ": "Johnson & Johnson",
    "JPM": "JPMorgan Chase",
    "V": "Visa",
    "PG": "Procter & Gamble",
    "MA": "Mastercard",
    "HD": "Home Depot",
    "CVX": "Chevron",
    "MRK": "Merck",
    "ABBV": "AbbVie",
    "PEP": "PepsiCo",
    "KO": "Coca-Cola",
    "AVGO": "Broadcom",
    "COST": "Costco",
    "WMT": "Walmart",
    "BAC": "Bank of America",
    "DIS": "Disney",
    "MCD": "McDonald's",
    "CSCO": "Cisco Systems",
    "PFE": "Pfizer",
    "TMO": "Thermo Fisher Scientific",
    "ACN": "Accenture",
    "DHR": "Danaher",
    "LIN": "Linde",
    "WFC": "Wells Fargo",
    "TXN": "Texas Instruments",
    "UPS": "United Parcel Service",
    "NEE": "NextEra Energy",
    "RTX": "RTX Corp",
    "IBM": "IBM",
    "INTC": "Intel",
    "AMD": "Advanced Micro Devices",
    "NFLX": "Netflix",
    "QCOM": "Qualcomm",
    "SBUX": "Starbucks",
    "AMAT": "Applied Materials",
    "LOW": "Lowe's",
    "CAT": "Caterpillar",
    "BLK": "BlackRock",
    "GE": "General Electric",
    "HON": "Honeywell",
    "BA": "Boeing",
    "MDT": "Medtronic",
    "SPGI": "S&P Global",
    "GS": "Goldman Sachs",
    "PLD": "Prologis",
    "ADBE": "Adobe",
    "NOW": "ServiceNow",
    "BKNG": "Booking Holdings",
    "ISRG": "Intuitive Surgical",
    "LMT": "Lockheed Martin",
    "EL": "Estee Lauder",
    "MO": "Altria",
    "DE": "Deere",
    "MMC": "Marsh & McLennan",
    "C": "Citigroup",
    "T": "AT&T",
    "VZ": "Verizon",
    "FDX": "FedEx",
    "SO": "Southern Company",
    "DUK": "Duke Energy",
    "AEP": "American Electric Power",
    "REGN": "Regeneron",
    "GILD": "Gilead Sciences",
    "VRTX": "Vertex Pharmaceuticals",
    "CSX": "CSX Corp",
    "NSC": "Norfolk Southern",
    "BDX": "Becton Dickinson",
    "CL": "Colgate-Palmolive",
    "MNST": "Monster Beverage",
    "KDP": "Keurig Dr Pepper",
    "WM": "Waste Management",
    "ADP": "Automatic Data Processing",
    "ORCL": "Oracle",
    "CRM": "Salesforce",
    "PANW": "Palo Alto Networks",
    "FTNT": "Fortinet",
    "HCA": "HCA Healthcare",
    "LRCX": "Lam Research",
    "MU": "Micron Technology",
    "ZTS": "Zoetis",
    "MAR": "Marriott",
    "ETN": "Eaton",
    "EMR": "Emerson Electric",
    "ROST": "Ross Stores",
    "TJX": "TJX Companies"
}
