# tickers.py
# 寄り付き天底狙い用：東証30銘柄＋米国30銘柄（合計60）

TICKERS = {
    # --- 東証（30銘柄） ---
    "7203.T": "トヨタ自動車",
    "6758.T": "ソニーグループ",
    "8306.T": "三菱UFJ FG",
    "7974.T": "任天堂",
    "9984.T": "ソフトバンクグループ",
    "6501.T": "日立製作所",
    "4502.T": "武田薬品工業",
    "6861.T": "キーエンス",
    "9983.T": "ファーストリテイリング",
    "8035.T": "東京エレクトロン",
    "6594.T": "日本電産",
    "9433.T": "KDDI",
    "9432.T": "NTT",
    "8316.T": "三井住友FG",
    "8058.T": "三菱商事",
    "8001.T": "伊藤忠商事",
    "8053.T": "住友商事",
    "8766.T": "東京海上HD",
    "4661.T": "オリエンタルランド",
    "7270.T": "SUBARU",
    "6902.T": "デンソー",
    "6981.T": "村田製作所",
    "7741.T": "HOYA",
    "6098.T": "リクルート",
    "4689.T": "Zホールディングス",
    "9101.T": "日本郵船",
    "9107.T": "川崎汽船",
    "9104.T": "商船三井",
    "5411.T": "JFEホールディングス",
    "5401.T": "日本製鉄",

    # --- 米国株（30銘柄） ---
    "AAPL": "Apple",
    "MSFT": "Microsoft",
    "GOOGL": "Alphabet",
    "AMZN": "Amazon",
    "META": "Meta Platforms",
    "TSLA": "Tesla",
    "NVDA": "NVIDIA",
    "AMD": "Advanced Micro Devices",
    "INTC": "Intel",
    "NFLX": "Netflix",
    "AVGO": "Broadcom",
    "QCOM": "Qualcomm",
    "CSCO": "Cisco Systems",
    "PEP": "PepsiCo",
    "KO": "Coca-Cola",
    "WMT": "Walmart",
    "JPM": "JPMorgan Chase",
    "BAC": "Bank of America",
    "C": "Citigroup",
    "XOM": "Exxon Mobil",
    "CVX": "Chevron",
    "HD": "Home Depot",
    "MCD": "McDonald's",
    "COST": "Costco",
    "SBUX": "Starbucks",
    "BA": "Boeing",
    "JNJ": "Johnson & Johnson",
    "PG": "Procter & Gamble",
    "V": "Visa",
    "MA": "Mastercard"
}
